### ISSUE TITLE
Update this JS SDK to support Promise

### ISSUE THREAD

**Issue by srameshr** [GetStream/Stream-Example-Parse#4]

**Comment by tschellenbach** [comment]
you know parse is shutting down right?

**Comment by srameshr** [comment]
Yeah! Still there is an year of time to switch!
But the Parse Server is open sourced. It should not be a problem to run ditto after exporting to AWS or something. So any updates to this JS lib?

**Comment by srameshr** [comment]
@tschellenbach Oh wait! I can just use the node.js library on top of this right?

**Comment by srameshr** [comment]
@tschellenbach Throws XMLHttpReq is not supported. But that part is for the browser! I see it in the Node.js library! Can you explain this?

**Comment by tschellenbach** [comment]
Hi,

The parse cloud code doesn't run node. They have their own APIs for making requests. 
This branch of the stream-js repo supports Parse cloud. You could update it with the changes from master and fix the resulting bugs:
https://github.com/getstream/stream-js/tree/parse
Since parse is being retired, we wont be supporting this branch anymore.
